[tool.ruff]
target-version = "py312"
line-length = 120
src = ["python-src"]

[tool.ruff.lint]
select = ["E", "W", "F", "I", "B", "S", "UP", "SIM"]

[tool.ruff.lint.per-file-ignores]
"python-src/tests/*" = ["S101"]

[tool.mypy]
python_version = "3.12"
check_untyped_defs = true
ignore_missing_imports = true
mypy_path = "python-src"

[tool.pytest.ini_options]
testpaths = ["python-src/tests"]
python_files = "test_*.py"
